name: simplelocalize
description: Simplelocalize.io CLI for dart projects
version: 0.2.0
homepage: https://github.com/TheMisir/simplelocalize-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
  dio: ^4.0.0

dev_dependencies:
  test: any
