name: simplelocalize
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/TheMisir/simplelocalize-flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  yaml: ^2.1.15
  path: ^1.7.0
  dio: ^3.0.0

dev_dependencies:
  test: ^1.11.1
